<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;
use App\Models\Question; 
class QuestionSeeder extends Seeder
{
    public function run(): void
    {
        $questions = [
           
           ['Texte_de_la_question' => 'Genre', 'Type_de_question' => 'single_choice', 'Options_de_Reponse' => json_encode(['a' => 'Masculin', 'b' => 'Féminin']),'Points_attribues' => json_encode(['a' => 0, 'b' => 0.25]), 'Ordre_affichage_dans_le_questionnaire' => 1, 'Dependances_de_question' => null], 
            ['Texte_de_la_question' => 'Âge', 'Type_de_question' => 'single_choice', 'Options_de_Reponse' => json_encode(['a' => 'Moins de 18 ans', 'b' => '18-25 ans', 'c' => '26-35 ans', 'd' => '36-45 ans', 'e' => '46-55 ans', 'f' => '56 ans et plus']), 'Points_attribues' => json_encode(['a' => 0, 'b' => 0.25,'c' => 0.5,'d' => 0.75, 'e' => 1,'f' => 1.25, ]), 'Ordre_affichage_dans_le_questionnaire' => 2, 'Dependances_de_question' => null],
            ['Texte_de_la_question' => 'État civil', 'Type_de_question' => 'single_choice', 'Options_de_Reponse' => json_encode(['a' => 'Célibataire', 'b' => 'Marié(e)', 'c' => 'Divorcé(e)', 'd' => 'Veuf/Veuve']), 'Points_attribues' => json_encode(['a' => 0, 'b' => 0.25,'c' => 0.5,'d' => 0.75, ]), 'Ordre_affichage_dans_le_questionnaire' => 3, 'Dependances_de_question' => null],
            ['Texte_de_la_question' => 'Niveau d\'éducation', 'Type_de_question' => 'single_choice', 'Options_de_Reponse' => json_encode(['a' => 'Études primaires', 'b' => 'Études secondaires', 'c' => 'Études supérieures (Baccalauréat, Licence, Master)', 'd' => 'Études postdoctorales (Doctorat)']), 'Points_attribues' => json_encode(['a' => 0, 'b' => 0.25,'c' => 0.5,'d' => 0.75, ]), 'Ordre_affichage_dans_le_questionnaire' => 4, 'Dependances_de_question' => null],
            ['Texte_de_la_question' => 'Situation professionnelle', 'Type_de_question' => 'single_choice', 'Options_de_Reponse' => json_encode(['a' => 'Étudiant', 'b' => 'Employé à plein temps', 'c' => 'Employé à temps partiel', 'd' => 'Indépendant/Entrepreneur', 'e' => 'Sans emploi', 'f' => 'Retraité(e)']), 'Points_attribues' => json_encode(['a' => 0, 'b' => 0.25,'c' => 0.5,'d' => 0.75, 'e' => 1,'f' => 1.25, ]), 'Ordre_affichage_dans_le_questionnaire' => 5, 'Dependances_de_question' => null],
            ['Texte_de_la_question' => 'Revenu annuel', 'Type_de_question' => 'single_choice', 'Options_de_Reponse' => json_encode(['a' => 'Moins de 10 000 DA', 'b' => '10 000 DA - 30 000 DA', 'c' => '30 000 DA - 60 000 DA', 'd' => '60 000 DA - 90 000 DA', 'e' => 'Plus de 90 000 DA']), 'Points_attribues' => json_encode(['a' => 0, 'b' => 0.25,'c' => 0.5,'d' => 0.75, 'e' => 1, ]), 'Ordre_affichage_dans_le_questionnaire' => 6, 'Dependances_de_question' => null],
            

            ['Texte_de_la_question' => 'À quelle fréquence jouez-vous aux jeux vidéo ?', 'Type_de_question' => 'single_choice', 'Options_de_Reponse' => json_encode(['a' => 'Moins d\'une heure par jour', 'b' => '1 à 2 heures par jour', 'c' => '2 à 4 heures par jour', 'd' => 'Plus de 4 heures par jour']), 'Points_attribues' => json_encode(['a' => 0, 'b' => 0.25,'c' => 0.5,'d' => 0.75, ]), 'Ordre_affichage_dans_le_questionnaire' => 7, 'Dependances_de_question' => null],
            ['Texte_de_la_question' => 'Quelle importance accordiez-vous aux jeux vidéo par rapport à d\'autres activités ?', 'Type_de_question' => 'single_choice', 'Options_de_Reponse' => json_encode(['a' => 'Moins importante', 'b' => 'Aussi importante', 'c' => 'Plus importante']), 'Points_attribues' => json_encode(['a' => 0, 'b' => 0.25,'c' => 0.5, ]), 'Ordre_affichage_dans_le_questionnaire' => 8, 'Dependances_de_question' => null],
            ['Texte_de_la_question' => 'Quel est l\'impact des jeux vidéo sur vos relations sociales ?', 'Type_de_question' => 'single_choice', 'Options_de_Reponse' => json_encode(['a' => 'Aucun impact', 'b' => 'Légère altération (moins de contact)', 'c' => 'Impact significatif (relations négligées)']), 'Points_attribues' => json_encode(['a' => 0, 'b' => 0.25,'c' => 0.5, ]), 'Ordre_affichage_dans_le_questionnaire' => 9, 'Dependances_de_question' => null],
            ['Texte_de_la_question' => 'Avez-vous déjà menti à propos du temps passé à jouer aux jeux vidéo ?', 'Type_de_question' => 'single_choice', 'Options_de_Reponse' => json_encode(['a' => 'Jamais', 'b' => 'Rarement', 'c' => 'Parfois', 'd' => 'Fréquemment']), 'Points_attribues' => json_encode(['a' => 0, 'b' => 0.25,'c' => 0.5,'d' => 0.75, ]), 'Ordre_affichage_dans_le_questionnaire' => 10, 'Dependances_de_question' => null],
            ['Texte_de_la_question' => 'Comment réagissez-vous lorsque vous ne pouvez pas jouer aux jeux vidéo ?', 'Type_de_question' => 'single_choice', 'Options_de_Reponse' => json_encode(['a' => 'Aucune réaction particulière', 'b' => 'Légère déception', 'c' => 'Irritabilité ou frustration', 'd' => 'Besoin urgent de jouer']), 'Points_attribues' => json_encode(['a' => 0, 'b' => 0.25,'c' => 0.5,'d' => 0.75, ]), 'Ordre_affichage_dans_le_questionnaire' => 11, 'Dependances_de_question' => null],
            ['Texte_de_la_question' => 'Avez-vous déjà ressenti un besoin croissant de jouer pour obtenir la même sensation de plaisir ou d\'excitation ?', 'Type_de_question' => 'single_choice', 'Options_de_Reponse' => json_encode(['a' => 'Non, jamais', 'b' => 'Rarement', 'c' => 'Parfois', 'd' => 'Fréquemment']), 'Points_attribues' => json_encode(['a' => 0, 'b' => 0.25,'c' => 0.5,'d' => 0.75, ]), 'Ordre_affichage_dans_le_questionnaire' => 12, 'Dependances_de_question' => null],
            ['Texte_de_la_question' => 'Dans quelle mesure les jeux vidéo affectent-ils votre sommeil ?', 'Type_de_question' => 'single_choice', 'Options_de_Reponse' => json_encode(['a' => 'Aucun impact', 'b' => 'Légère perturbation', 'c' => 'Insomnie occasionnelle', 'd' => 'Insomnie fréquente']),'Points_attribues' => json_encode(['a' => 0, 'b' => 0.25,'c' => 0.5,'d' => 0.75, ]), 'Ordre_affichage_dans_le_questionnaire' => 13, 'Dependances_de_question' => null],
            ['Texte_de_la_question' => 'Avez-vous déjà négligé des responsabilités professionnelles ou scolaires à cause des jeux vidéo ?', 'Type_de_question' => 'single_choice', 'Options_de_Reponse' => json_encode(['a' => 'Jamais', 'b' => 'Rarement', 'c' => 'Parfois', 'd' => 'Fréquemment']), 'Points_attribues' => json_encode(['a' => 0, 'b' => 0.25,'c' => 0.5,'d' => 0.75, ]), 'Ordre_affichage_dans_le_questionnaire' => 14, 'Dependances_de_question' => null],
            ['Texte_de_la_question' => 'Avez-vous essayé de réduire votre temps de jeu sans succès ?', 'Type_de_question' => 'single_choice', 'Options_de_Reponse' => json_encode(['a' => 'Oui, avec succès', 'b' => 'Oui, mais sans succès', 'c' => 'Non, je n\'ai pas essayé']), 'Points_attribues' => json_encode(['a' => 0, 'b' => 0.25,'c' => 0.5,]), 'Ordre_affichage_dans_le_questionnaire' => 15, 'Dependances_de_question' => null],
            ['Texte_de_la_question' => 'Comment vous sentez-vous lorsque vous ne jouez pas aux jeux vidéo pendant une longue période ?', 'Type_de_question' => 'single_choice', 'Options_de_Reponse' => json_encode(['a' => 'Indifférent', 'b' => 'Ennui léger', 'c' => 'Irritabilité ou agitation', 'd' => 'Dépression ou anxiété']),'Points_attribues' => json_encode(['a' => 0, 'b' => 0.25,'c' => 0.5,'d' => 0.75, ]), 'Ordre_affichage_dans_le_questionnaire' => 16, 'Dependances_de_question' => null],
            ['Texte_de_la_question' => 'Avez-vous déjà emprunté de l\'argent pour acheter des jeux vidéo ou du contenu lié aux jeux ?', 'Type_de_question' => 'single_choice', 'Options_de_Reponse' => json_encode(['a' => 'Jamais', 'b' => 'Rarement', 'c' => 'Parfois', 'd' => 'Fréquemment']),'Points_attribues' => json_encode(['a' => 0, 'b' => 0.25,'c' => 0.5,'d' => 0.75, ]), 'Ordre_affichage_dans_le_questionnaire' => 17, 'Dependances_de_question' => null],
            ['Texte_de_la_question' => 'Comment décririez-vous votre niveau de concentration pendant que vous jouez aux jeux vidéo ?', 'Type_de_question' => 'single_choice', 'Options_de_Reponse' => json_encode(['a' => 'Excellente', 'b' => 'Bonne', 'c' => 'Moyenne', 'd' => 'Faible']), 'Points_attribues' => json_encode(['a' => 0, 'b' => 0.25,'c' => 0.5,'d' => 0.75, ]), 'Ordre_affichage_dans_le_questionnaire' => 18, 'Dependances_de_question' => null],
            ['Texte_de_la_question' => 'Avez-vous déjà ressenti des symptômes physiques tels que des maux de tête, des douleurs musculaires ou des troubles de la vision à cause d\'une session de jeu prolongée ?', 'Type_de_question' => 'single_choice', 'Options_de_Reponse' => json_encode(['a' => 'Jamais', 'b' => 'Rarement', 'c' => 'Parfois', 'd' => 'Fréquemment']), 'Points_attribues' => json_encode(['a' => 0, 'b' => 0.25,'c' => 0.5,'d' => 0.75, ]), 'Ordre_affichage_dans_le_questionnaire' => 19, 'Dependances_de_question' => null],
            ['Texte_de_la_question' => 'Les jeux vidéo ont-ils eu un impact négatif sur votre productivité au travail ou à l\'école ?', 'Type_de_question' => 'single_choice', 'Options_de_Reponse' => json_encode(['a' => 'Aucun impact', 'b' => 'Léger impact', 'c' => 'Impact modéré', 'd' => 'Impact significatif']), 'Points_attribues' => json_encode(['a' => 0, 'b' => 0.25,'c' => 0.5,'d' => 0.75, ]), 'Ordre_affichage_dans_le_questionnaire' => 20, 'Dependances_de_question' => null],
            ['Texte_de_la_question' => 'Combien de fois avez-vous négligé des activités importantes pour jouer aux jeux vidéo (ex : hygiène personnelle, tâches ménagères) ?', 'Type_de_question' => 'single_choice', 'Options_de_Reponse' => json_encode(['a' => 'Jamais', 'b' => 'Rarement', 'c' => 'Parfois', 'd' => 'Fréquemment']), 'Points_attribues' => json_encode(['a' => 0, 'b' => 0.25,'c' => 0.5,'d' => 0.75, ]), 'Ordre_affichage_dans_le_questionnaire' => 21, 'Dependances_de_question' => null],
            ['Texte_de_la_question' => 'Avez-vous déjà eu des disputes familiales ou des conflits avec des amis à cause de votre temps passé à jouer aux jeux vidéo ?', 'Type_de_question' => 'single_choice', 'Options_de_Reponse' => json_encode(['a' => 'Jamais', 'b' => 'Rarement', 'c' => 'Parfois', 'd' => 'Fréquemment']), 'Points_attribues' => json_encode(['a' => 0, 'b' => 0.25,'c' => 0.5,'d' => 0.75, ]), 'Ordre_affichage_dans_le_questionnaire' => 22, 'Dependances_de_question' => null],
            ['Texte_de_la_question' => 'Quel est votre état émotionnel après avoir joué à des jeux vidéo pendant de longues périodes ?', 'Type_de_question' => 'single_choice', 'Options_de_Reponse' => json_encode(['a' => 'Énergisé et heureux', 'b' => 'Fatigué mais satisfait', 'c' => 'Irrité ou déprimé', 'd' => 'Anxieux ou stressé']), 'Points_attribues' => json_encode(['a' => 0, 'b' => 0.25,'c' => 0.5,'d' => 0.75, ]), 'Ordre_affichage_dans_le_questionnaire' => 23, 'Dependances_de_question' => null],
            ['Texte_de_la_question' => 'Avez-vous déjà manqué des événements sociaux pour jouer aux jeux vidéo ?', 'Type_de_question' => 'single_choice', 'Options_de_Reponse' => json_encode(['a' => 'Jamais', 'b' => 'Rarement', 'c' => 'Parfois', 'd' => 'Fréquemment']), 'Points_attribues' => json_encode(['a' => 0, 'b' => 0.25,'c' => 0.5,'d' => 0.75, ]), 'Ordre_affichage_dans_le_questionnaire' => 24, 'Dependances_de_question' => null],
            ['Texte_de_la_question' => 'Avez-vous développé des routines spécifiques ou des rituels avant ou pendant le jeu vidéo (ex : superstitions, préparation spécifique) ?', 'Type_de_question' => 'single_choice', 'Options_de_Reponse' => json_encode(['a' => 'Jamais', 'b' => 'Rarement', 'c' => 'Parfois', 'd' => 'Fréquemment']), 'Points_attribues' => json_encode(['a' => 0, 'b' => 0.25,'c' => 0.5,'d' => 0.75, ]), 'Ordre_affichage_dans_le_questionnaire' => 25, 'Dependances_de_question' => null],
            ['Texte_de_la_question' => 'Ressentez-vous le besoin constant de vérifier les mises à jour, les nouvelles versions ou les annonces de jeux vidéo ?', 'Type_de_question' => 'single_choice', 'Options_de_Reponse' => json_encode(['a' => 'Jamais', 'b' => 'Rarement', 'c' => 'Parfois', 'd' => 'Fréquemment']), 'Points_attribues' => json_encode(['a' => 0, 'b' => 0.25,'c' => 0.5,'d' => 0.75, ]), 'Ordre_affichage_dans_le_questionnaire' => 26, 'Dependances_de_question' => null],
            ['Texte_de_la_question' => 'Combien de temps par jour passez-vous à penser aux jeux vidéo lorsque vous ne jouez pas ?', 'Type_de_question' => 'single_choice', 'Options_de_Reponse' => json_encode(['a' => 'Quasiment jamais', 'b' => 'Moins d\'une heure', 'c' => '1 à 2 heures', 'd' => 'Plus de 2 heures']), 'Points_attribues' => json_encode(['a' => 0, 'b' => 0.25,'c' => 0.5,'d' => 0.75, ]), 'Ordre_affichage_dans_le_questionnaire' => 27, 'Dependances_de_question' => null],
            ['Texte_de_la_question' => 'Avez-vous déjà caché ou minimisé la quantité de temps que vous passez à jouer aux jeux vidéo à vos proches ?', 'Type_de_question' => 'single_choice', 'Options_de_Reponse' => json_encode(['a' => 'Jamais', 'b' => 'Rarement', 'c' => 'Parfois', 'd' => 'Fréquemment']), 'Points_attribues' => json_encode(['a' => 0, 'b' => 0.25,'c' => 0.5,'d' => 0.75, ]), 'Ordre_affichage_dans_le_questionnaire' => 28, 'Dependances_de_question' => null],
            ['Texte_de_la_question' => 'Ressentez-vous souvent de la culpabilité après avoir joué aux jeux vidéo pour une longue période ?', 'Type_de_question' => 'single_choice', 'Options_de_Reponse' => json_encode(['a' => 'Jamais', 'b' => 'Rarement', 'c' => 'Parfois', 'd' => 'Fréquemment']), 'Points_attribues' => json_encode(['a' => 0, 'b' => 0.25,'c' => 0.5,'d' => 0.75, ]), 'Ordre_affichage_dans_le_questionnaire' => 29, 'Dependances_de_question' => null],
            ['Texte_de_la_question' => 'Avez-vous déjà manqué des engagements personnels ou professionnels en raison de sessions de jeu prolongées ?', 'Type_de_question' => 'single_choice', 'Options_de_Reponse' => json_encode(['a' => 'Jamais', 'b' => 'Rarement', 'c' => 'Parfois', 'd' => 'Fréquemment']), 'Points_attribues' => json_encode(['a' => 0, 'b' => 0.25,'c' => 0.5,'d' => 0.75, ]), 'Ordre_affichage_dans_le_questionnaire' => 30, 'Dependances_de_question' => null],
            ['Texte_de_la_question' => 'Avez-vous eu des problèmes de mémoire ou de concentration en dehors du jeu après une session de jeu prolongée ?', 'Type_de_question' => 'single_choice', 'Options_de_Reponse' => json_encode(['a' => 'Jamais', 'b' => 'Rarement', 'c' => 'Parfois', 'd' => 'Fréquemment']),'Points_attribues' => json_encode(['a' => 0, 'b' => 0.25,'c' => 0.5,'d' => 0.75, ]), 'Ordre_affichage_dans_le_questionnaire' => 31, 'Dependances_de_question' => null],
            ['Texte_de_la_question' => 'Les jeux vidéo ont-ils eu un impact négatif sur votre vie sentimentale ?', 'Type_de_question' => 'single_choice', 'Options_de_Reponse' => json_encode(['a' => 'Aucun impact', 'b' => 'Léger impact', 'c' => 'Impact modéré', 'd' => 'Impact significatif']), 'Points_attribues' => json_encode(['a' => 0, 'b' => 0.25,'c' => 0.5,'d' => 0.75, ]), 'Ordre_affichage_dans_le_questionnaire' => 32, 'Dependances_de_question' => null],
            ['Texte_de_la_question' => 'Avez-vous déjà sacrifié des activités physiques ou sportives pour jouer aux jeux vidéo ?', 'Type_de_question' => 'single_choice', 'Options_de_Reponse' => json_encode(['a' => 'Jamais', 'b' => 'Rarement', 'c' => 'Parfois', 'd' => 'Fréquemment']),'Points_attribues' => json_encode(['a' => 0, 'b' => 0.25,'c' => 0.5,'d' => 0.75, ]), 'Ordre_affichage_dans_le_questionnaire' => 33, 'Dependances_de_question' => null],
            ['Texte_de_la_question' => 'Ressentez-vous le besoin de jouer aux jeux vidéo pour échapper à des problèmes ou à des sentiments négatifs ?', 'Type_de_question' => 'single_choice', 'Options_de_Reponse' => json_encode(['a' => 'Jamais', 'b' => 'Rarement', 'c' => 'Parfois', 'd' => 'Fréquemment']), 'Points_attribues' => json_encode(['a' => 0, 'b' => 0.25,'c' => 0.5,'d' => 0.75, ]), 'Ordre_affichage_dans_le_questionnaire' => 34, 'Dependances_de_question' => null],
            ['Texte_de_la_question' => 'Avez-vous déjà ressenti des sautes d\'humeur importantes lorsque vous ne pouviez pas jouer aux jeux vidéo ?', 'Type_de_question' => 'single_choice', 'Options_de_Reponse' => json_encode(['a' => 'Jamais', 'b' => 'Rarement', 'c' => 'Parfois', 'd' => 'Fréquemment']), 'Points_attribues' => json_encode(['a' => 0, 'b' => 0.25,'c' => 0.5,'d' => 0.75, ]), 'Ordre_affichage_dans_le_questionnaire' => 35, 'Dependances_de_question' => null],
            ['Texte_de_la_question' => 'Comment évalueriez-vous votre niveau de dépendance ou d\'attachement émotionnel aux jeux vidéo ?', 'Type_de_question' => 'single_choice', 'Options_de_Reponse' => json_encode(['a' => 'Faible', 'b' => 'Modéré', 'c' => 'Élevé', 'd' => 'Très élevé']), 'Points_attribues' => json_encode(['a' => 0, 'b' => 0.25,'c' => 0.5,'d' => 0.75, ]), 'Ordre_affichage_dans_le_questionnaire' => 36, 'Dependances_de_question' => null],
                              
        ];
        foreach ($questions as $question) {
            DB::table('questions')->insert($questions);
        }
    }
}